INSERT INTO productos (nombre, descripcion, precio, marca, stock) VALUES
('Sofá de Tela Gris', 'Sofá de tres plazas con tela suave y cómoda.', 499.99, 'Muebles Elegantes', 15),
('Mesa de Centro de Madera', 'Mesa de centro rectangular con acabado de madera natural.', 129.95, 'Diseños Modernos', 20),
('Silla de Comedor Acolchada', 'Silla acolchada con respaldo alto para mayor comodidad.', 79.99, 'Confort Living', 25),
('Librero de Roble', 'Estantería de roble con estantes ajustables.', 349.50, 'Muebles Duraderos', 10),
('Cama King Size de Cuero', 'Cama king size con cabecero tapizado en cuero negro.', 799.99, 'Estilo Contemporáneo', 8),
('Armario Empotrado de Madera', 'Armario empotrado con puertas de madera y cajones integrados.', 699.95, 'Diseño Clásico', 12),
('Mesa de Escritorio con Cajones', 'Mesa de escritorio con cajones para almacenamiento adicional.', 189.99, 'Oficina Efectiva', 18),
('Sillón Reclinable de Tela', 'Sillón reclinable con tela suave y mecanismo de inclinación.', 299.50, 'Relax Comfort', 5),
('Mesa de Comedor Extensible', 'Mesa de comedor extensible para adaptarse a más invitados.', 449.99, 'Espacios Amplios', 15),
('Estantería Modular', 'Estantería modular con unidades independientes para personalización.', 219.75, 'Diseño Versátil', 22),
('Mesa Auxiliar de Vidrio', 'Mesa auxiliar con superficie de vidrio templado.', 69.99, 'Diseño Elegante', 25),
('Silla Giratoria de Oficina', 'Silla de oficina ergonómica con mecanismo giratorio.', 129.50, 'Trabajo Productivo', 18),
('Cómoda de Cajones', 'Cómoda con cajones espaciosos y tiradores de metal.', 179.95, 'Almacenamiento Eficiente', 10),
('Sofá Cama Moderno', 'Sofá que se convierte en cama individual, perfecto para espacios pequeños.', 349.99, 'Funcionalidad Práctica', 12),
('Espejo de Pared Decorativo', 'Espejo rectangular con marco decorativo.', 49.75, 'Estilo Refinado', 30),
('Mesa de Noche de Madera', 'Mesa de noche con un cajón y estante inferior.', 89.99, 'Noches Tranquilas', 15),
('Silla Plegable de Exterior', 'Silla plegable para uso en exteriores, resistente a la intemperie.', 44.50, 'Aire Libre Comfortable', 20),
('Mesa de Comedor Redonda', 'Mesa de comedor redonda con patas de metal.', 289.95, 'Estilo Moderno', 8),
('Armario de Almacenamiento', 'Armario con puertas y estantes para almacenamiento versátil.', 239.99, 'Organización Práctica', 15),
('Lámpara Colgante de Cristal', 'Lámpara colgante con detalles de cristal para iluminación elegante.', 119.50, 'Ambiente Sofisticado', 12),
('Estantería de Esquina', 'Estantería diseñada para ajustarse en esquinas, maximizando el espacio.', 79.99, 'Optimización del Espacio', 18),
('Mesa de Centro de Vidrio', 'Mesa de centro con superficie de vidrio y base de metal.', 159.95, 'Estilo Minimalista', 25),
('Sofá de Cuero Seccional', 'Sofá seccional con asientos reclinables y tapizado en cuero.', 799.99, 'Lujo Confortable', 10),
('Mueble para TV', 'Mueble para TV con espacio para almacenamiento y estantes.', 269.50, 'Entretenimiento en Casa', 15),
('Lámpara de Mesa de Cerámica', 'Lámpara de mesa con base de cerámica y pantalla de tela.', 69.75, 'Decoración Acogedora', 20),
('Mesa de Comedor Ovalada', 'Mesa de comedor ovalada con patas de acero inoxidable.', 349.99, 'Elegancia Moderna', 15),
('Sillón de Lectura Acolchado', 'Sillón cómodo para lectura con cojín acolchado.', 129.99, 'Descanso Placentero', 12),
('Mesa de Café con Ruedas', 'Mesa de café con ruedas para mayor movilidad.', 89.50, 'Diseño Funcional', 20),
('Cómoda de Madera Maciza', 'Cómoda de madera maciza con detalles tallados.', 299.95, 'Artesanía Clásica', 8),
('Sofá Modular de Tela', 'Sofá modular con secciones reconfigurables.', 599.50, 'Versatilidad Decorativa', 10),
('Lámpara de Pie Industrial', 'Lámpara de pie con estilo industrial y regulador de intensidad.', 119.99, 'Estilo Urbano', 25);
